#define TOKEN_ETF                             1
#define TOKEN_ERROR                           2
#define TOKEN_BEGIN                           3
#define TOKEN_STATE                           4
#define TOKEN_END                             5
#define TOKEN_EDGE                            6
#define TOKEN_INIT                            7
#define TOKEN_NUMBER                          8
#define TOKEN_STRING                          9
#define TOKEN_IDENT                          10
#define TOKEN_COLON                          11
#define TOKEN_SORT                           12
#define TOKEN_VALUE                          13
#define TOKEN_TRANS                          14
#define TOKEN_MAP                            15
#define TOKEN_END_OF_LINE                    16
#define TOKEN_STAR                           17
#define TOKEN_SLASH                          18
#define TOKEN_EXPR                           19
#define TOKEN_QUANTIFIER                     20
#define TOKEN_BIN3                           21
#define TOKEN_BIN2                           22
#define TOKEN_BIN1                           23
#define TOKEN_LPAR                           24
#define TOKEN_RPAR                           25
#define TOKEN_STATE_VAR                      26
#define TOKEN_EDGE_VAR                       27
#define TOKEN_MU_SYM                         28
#define TOKEN_DOT                            29
#define TOKEN_NU_SYM                         30
#define TOKEN_EXISTS_SYM                     31
#define TOKEN_ALL_SYM                        32
#define TOKEN_IF                             33
#define TOKEN_THEN                           34
